server:
  port: 8088

spring:
  application:
    name: marketing-auth-api-server
  profiles:
    group:
      local: cognito-local
      prod: cognito-prod
      aws: cognito-aws
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_Sw2F1HsU7/.well-known/jwks.json
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_Sw2F1HsU7

# Cognito 설정
cognito:
  region: ap-northeast-2
  userPoolId: ap-northeast-2_Sw2F1HsU7
  clientId: 4jup717oq1ckpogobq768o7r6c

